---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-fs-stub
  name: pttg-fs-stub
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
    targetPort: 10443
  selector:
    name: pttg-fs-stub
